repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: mixed-line-ending
        name: Fix mixed line ending
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: Remove extra EOF newlines
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        name: Format with clang-format
        args: [-style=file, -i]
